### ISSUE TITLE
如何修改快捷键啊？

### ISSUE THREAD

**Issue by 1457384613gh** [SamuelYG/CrScreenshotDxe-Update#1]
如何修改快捷键啊？
我想改成【F10】

**Comment by YangGangSam** [comment]
热键/快捷键注册是在这里

https://github.com/YangGangSam/CrScreenshotDxe-Update/blob/1b6acfab82ae6b83276344c17c5d701d259399e1/CrScreenshotDxe.c#L336-L343

如果只用 F10 

338 行修改为如下：
`SimpleTextInExKeyStroke.Key.ScanCode = SCAN_F10;`

然后 341 行注释掉应该就行了。

现在不确定这份代码的可用程度。原始上游仓库好像有更新，可以看一看。https://github.com/LongSoft/CrScreenshotDxe

后面有时间可能会重新写一个类似的模块。（如果有的话应该会放在这个账号下 @YangGangUEFI）

**Comment by YangGangSam** [comment]
这个 issue 先关闭了。
